//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulf_Hajj_and_Ummrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class billing_details_tbl
    {
        public int id { get; set; }
        public string detail_of_payment { get; set; }
        public string total_amount { get; set; }
        public string payment_type { get; set; }
        public string amount_recieved { get; set; }
        public string amount_pending { get; set; }
        public string expense { get; set; }
        public string profit_loss { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual client_details_tbl client_details_tbl { get; set; }
    }
}
