//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulf_Hajj_and_Ummrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class client_details_tbl
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public client_details_tbl()
        {
            this.billing_details_tbl = new HashSet<billing_details_tbl>();
            this.flight_details_tbl = new HashSet<flight_details_tbl>();
            this.hotel_details_tbl = new HashSet<hotel_details_tbl>();
            this.package_details_tbl = new HashSet<package_details_tbl>();
            this.transportation_details_tbl = new HashSet<transportation_details_tbl>();
            this.group_of_people_details_tbl = new HashSet<group_of_people_details_tbl>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string dispatched_to { get; set; }
        public string phone_number { get; set; }
        public string address { get; set; }
        public string shirka { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string passport_doc { get; set; }
        public string picture { get; set; }
        public string reference_by { get; set; }
        public string reference_contact_number { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<billing_details_tbl> billing_details_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<flight_details_tbl> flight_details_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hotel_details_tbl> hotel_details_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<package_details_tbl> package_details_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<transportation_details_tbl> transportation_details_tbl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<group_of_people_details_tbl> group_of_people_details_tbl { get; set; }
    }
}
