//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulf_Hajj_and_Ummrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hotel_details_tbl
    {
        public int id { get; set; }
        public string hotel_name { get; set; }
        public Nullable<System.TimeSpan> checkin_time { get; set; }
        public Nullable<System.TimeSpan> checkout_time { get; set; }
        public Nullable<int> city_id { get; set; }
        public Nullable<int> roomtype_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual cities_tbl cities_tbl { get; set; }
        public virtual client_details_tbl client_details_tbl { get; set; }
        public virtual roomtype_tbl roomtype_tbl { get; set; }
    }
}
