//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gulf_Hajj_and_Ummrah.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class package_details_tbl
    {
        public int id { get; set; }
        public string package_name { get; set; }
        public string no_of_days { get; set; }
        public Nullable<System.DateTime> date_of_departure { get; set; }
        public Nullable<System.DateTime> date_of_arrival { get; set; }
        public string pnr { get; set; }
        public string other_details { get; set; }
        public Nullable<int> airline_id { get; set; }
        public Nullable<int> client_id { get; set; }
        public Nullable<bool> isDeleted { get; set; }
    
        public virtual client_details_tbl client_details_tbl { get; set; }
    }
}
